import React, { useState } from 'react';

import { ShortenedUrl, ShortenedUrlNotification } from '@/components';
import { IShortenedUrl } from '@/interfaces';
import { Box, Heading, Container, Text, Stack, Flex } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  const [shortenedUrls, setShortenedUrls] = useState<IShortenedUrl[]>([]);

  const handleShortenedUrl = (urls: IShortenedUrl) =>
    setShortenedUrls((data) => [...data, urls]);

  return (
    <>
      <Head>
        <title>URL Shortener</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Container as='main' maxW={'3xl'}>
        <Stack
          as={Box}
          textAlign={'center'}
          spacing={{ base: 8, md: 10 }}
          py={{ base: 20, md: 36 }}
        >
          <Heading
            fontWeight={700}
            fontSize={{ base: '2xl', sm: '4xl', md: '6xl' }}
          >
            Criar links curtos
          </Heading>
          <Text color={'gray.500'}>
            Encurte seus links com mais rapidez e felicidade
          </Text>
          <ShortenedUrl onShortenedUrl={handleShortenedUrl} />

          <Flex direction='column' gap={5}>
            {shortenedUrls.map((item) => (
              <ShortenedUrlNotification
                key={item.shortenedUrl}
                originalUrl={item.originalUrl}
                shortenedUrl={item.shortenedUrl}
              />
            ))}
          </Flex>
        </Stack>
      </Container>
    </>
  );
};

export default Home;
